name: d2d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - python-dotenv
  - jupyter
  - pytorch
  - sentence-transformers
  - litellm
  - pytest  # Development only
  - pytest-subtests # Development only
  - pytest-asyncio  # Development only
  - pytest-mock  # Development only
  - rapidfuzz
  - dash=3.0.4
  - dash-bootstrap-components=2.0.3