name: d2d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - python-dotenv
  - jupyter
  - pytorch
  - sentence-transformers
  - openai
  - anthropic