# Although this package is currently focused on Python virtual environments (py env),
# the following dependency is included for potential future development needs.
# Remove if confirmed unnecessary in the future.

name: d2d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.4
  - pandas=1.5.3
  - python-dotenv
  - jupyter
  - pytorch
  - sentence-transformers
  - litellm
  - pytest  # Development only
  - pytest-subtests  # Development only
  - pytest-asyncio  # Development only
  - pytest-mock  # Development only
  - rapidfuzz
  - dash=3.0.4
  - dash-bootstrap-components=2.0.3