name: d2d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - python-dotenv
  - jupyter
  - pytorch
  - sentence-transformers
  - openai # To be deleted
  - anthropic # To be deleted
  - litellm
  - pytest  # Development only
  - pytest-subtests # Development only
  - rapidfuzz
