<!--
To render the PDF, please run
$ quarto render docs/reports/final_report/d2d_final_report.qmd --to pdf
The generated PDF will appear in the reports/ directory.
-->

---
title: | 
  Dialogue2Data (D2D): \ 
  Transforming Interviews into Structured Data \ 
  Final Project Report
author: "Sienko Ikhabi, Dominic Lam, Wangkai Zhu, Yun Zhou"
format:
    pdf:
        toc: true
        toc-depth: 3
        number-sections: true
execute:
  echo: false
  warning: false
---

\newpage

# Executive Summary

{{< include _executive_summary.qmd >}}

\newpage

# Project Introduction

{{< include _project_introduction.qmd >}}

\newpage

# Data Science Methods

## Overview

{{< include _ds_methods_overview.qmd >}}

## Processing Framework

{{< include _ds_methods_processor.qmd >}}

## Evaluation Framework

{{< include _ds_methods_evaluation.qmd >}}

\newpage

# Data Product and Results

## Description of Data Product

{{< include _data_product_description.qmd >}}

## Key Results

{{< include _key_results.qmd >}}

## Future Improvements

{{< include _data_product_future_work.qmd >}}

\newpage

# Conclusion and Recommendations

{{< include _conclusion.qmd >}}

\newpage

# References

- [1] S. Es, J. James, L. Espinosa-Anke, and S. Schockaert, “RAGAS: Automated Evaluation of Retrieval Augmented Generation,” arXiv preprint arXiv:2309.15217, Sep. 2023. [Online]. Available: https://doi.org/10.48550/arXiv.2309.15217    
- [2] DS-Daedalus Team, "DS-Daedalus v4: Increments and Updates," Internal Presentation Report, Mar. 2025